version: '3'

services:

    database:
      build: ./database
      container_name: database
      restart: always
      ports:
        - "3306:3306"
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: todoDB
      networks:
        - spring_net

    backend:
      build: ./back
      container_name: backend
      restart: always
      depends_on:
        - database
      ports:
        - "8080:8080"
      networks:
        - spring_net
    
    frontend:
      build: ./front
      container_name: frontend
      restart: always
      depends_on:
        - backend
      ports:
        - "3000:3000"
      networks:
        - spring_net
      
networks:
  spring_net: